[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["jdk17", "maven"]

[build.nixpacksPlan.phases.build]
cmds = ["cd javabite-backend && mvn clean package -DskipTests"]

[deploy]
startCommand = "java -Xmx512m -jar javabite-backend/target/javabite-backend-1.0.0.jar"
